export const tokens = {
  colors: {
    bgPrimary: 'var(--color-bg-primary)',
    bgSecondary: 'var(--color-bg-secondary)',
    bgCard: 'var(--color-bg-card)',
    bgCardHover: 'var(--color-bg-card-hover)',
    textPrimary: 'var(--color-text-primary)',
    textSecondary: 'var(--color-text-secondary)',
    textMuted: 'var(--color-text-muted)',
    accentPrimary: 'var(--color-accent-primary)',
    accentSuccess: 'var(--color-accent-success)',
    accentSuccessLight: 'var(--color-accent-success-light)',
    accentWarning: 'var(--color-accent-warning)',
    accentError: 'var(--color-accent-error)',
    borderDefault: 'var(--color-border-default)',
    borderAccent: 'var(--color-border-accent)',
    aws: 'var(--color-aws)',
    azure: 'var(--color-azure)',
    gcp: 'var(--color-gcp)',
    onprem: 'var(--color-onprem)',
  },
  spacing: {
    xs: 'var(--spacing-xs)',
    sm: 'var(--spacing-sm)',
    md: 'var(--spacing-md)',
    lg: 'var(--spacing-lg)',
    xl: 'var(--spacing-xl)',
    '2xl': 'var(--spacing-2xl)',
  },
  radius: {
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)',
    '2xl': 'var(--radius-2xl)',
    full: 'var(--radius-full)',
  },
} as const;
